### ISSUE TITLE
Map Persists But Character Did Not

### ISSUE THREAD

**Issue by pogzie** [tokkenno/windward-docker#1]
Hi, I was using this image as this proves to be more reliable on the other one. I have been running my Windward instance for more or less a week without problems but today I had to install a new networking equipment and had to stop the Docker container (made sure that my map states are saved) and proceeded to do my maintenance. 

Upon connecting again (same PC, same IP, same Docker container) the map loaded fine and showed all the regions I was able to visit/capture but im back to level 0. What gives?

**Comment by tokkenno** [comment]
Hi @pogzie . I only tried this docker for a while and I don't think I ever restarted it. You may need to mount some more folders as volume to persist it. Now I'm too busy to look at it. If you find the solution let me know to fix it.

**Comment by pogzie** [comment]
Yes you are correct. A painful reminder to make sure the correct volumes are mounted. Closing this. 

Hope you keep this updated. Dockerhub policy is cleaning up images every 6 mo. I still use your image. Thanks!

**Comment by tokkenno** [comment]
I've updated the image to ensure Docker Hub doesn't erase it. I no longer use this server, but if it is deleted in the future from Docker Hub, please let me know and I will update it.
